# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchstep < Formula
  desc "YAML-first workflow orchestration engine"
  homepage "https://orchstep.dev"
  version "0.2.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orchstep/orchstep/releases/download/v0.2.0/orchstep_0.2.0_darwin_amd64.tar.gz"
      sha256 "e0691d351b72d0467c6fa12c6d3203320183537c67b10b548a3dd33617ab1682"

      define_method(:install) do
        bin.install "orchstep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orchstep/orchstep/releases/download/v0.2.0/orchstep_0.2.0_darwin_arm64.tar.gz"
      sha256 "8a486d20967f83731774355f686a046dfa69d80278607118ddb3cfd28e83d365"

      define_method(:install) do
        bin.install "orchstep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchstep/orchstep/releases/download/v0.2.0/orchstep_0.2.0_linux_amd64.tar.gz"
      sha256 "4a58b46794fea8bb5f68e1b22bf194eb88950b6938d32f5dd347e59ae27e380f"
      define_method(:install) do
        bin.install "orchstep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchstep/orchstep/releases/download/v0.2.0/orchstep_0.2.0_linux_arm64.tar.gz"
      sha256 "002323bb6ceed02068ca9fd3fc58f1e30195196c53f7b5923a739949be77adbf"
      define_method(:install) do
        bin.install "orchstep"
      end
    end
  end

  test do
    system "#{bin}/orchstep", "version"
  end
end
